---

title: Meagan Voulo's Site
email: meagvo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Check out Meagan's data science and data analytics projects using python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  meagvo

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

---
